apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: demo
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
