- name: playbook
  hosts: myhosts
  remote_user: azure
  become: true
  tasks:
  - name: Copy file
    copy:
      src: ~/ansible/default
      dest: /etc/nginx/sites-enabled/default
  - name: nginx -t
    shell: nginx -t
    register: result
    ignore_errors: true
  - name: Print message
    ansible.builtin.debug:
      msg: "{{ result }}"
  - name: Restart service nginx
    service:
      name: nginx
      state: restarted
    when: not result.rc