- name: my first playbook
  hosts: myhosts
  remote_user: azure
  vars_prompt:
    - name: username
      prompt: "What is your username?"
      private: no
    - name: password
      prompt: "What is your password?"

  tasks:
    - debug:
        msg: 'Logging in as {{ username }}'
    - debug:
        msg: 'Logging in as {{ password }}'