- name: my first playbook
  hosts: myhosts
  remote_user: azure
  vars:
    myname: Prominent
  vars_files: 
  - external_vars.yaml
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print name
      ansible.builtin.debug:
        msg: Hello {{ myname }}

    - name: Print city
      ansible.builtin.debug:
        msg: Hello {{ city }}